---
server:
  port: 8080

logging:
  file: /tmp/demo-client.log

spring:
  application:
    name: demo-client
  profiles:
    active: secure
  boot:
    admin:
      url: http://localhost:8000/
      routes:
        endpoints:
         - env
         - metrics
         - trace
         - dump
         - jolokia
         - info
         - configprops
         - trace
         - logfile
         - refresh
         - flyway
         - liquibase
         - heapdump
         - loggers
         - currentTime
---
spring:
  profiles: insecure

management:
  security:
    enabled: false

security:
  basic:
    enabled: false
---
spring:
  profiles: secure
  boot:
    admin:
      username: admin       #These two are needed so that the client
      password: serverpass  #can register at the protected server api
      client:
        metadata:
          user.name: "${security.user.name}"          #These two are needed so that the server
          user.password:  "${security.user.password}" #can access the proteceted client endpoints

security:
  user:
    name: user
    password: clientpass
